### ISSUE TITLE
Unsure of how to set command prefix because of minimal documentation

### ISSUE THREAD

**Issue by akinauphill** [Greenadine/acf-javacord#1]
Hi, 
I've just added this to my bot project with Gradle, I have experience using ACF for Minecraft server's but never on anything else, I'm not sure of how to set the prefix and I can't find it anywhere, making my commands useless at the moment.

**Comment by Greenadine** [comment]
Hi, sorry for the late reply.

To manage which prefixes are allowed for commands, you have to create a custom command config, like this:

**Comment by Greenadine** [comment]
Hi, sorry for the late reply.

To manage which prefixes can be used for your bot's commands, you have to create a custom command config class, like this:
```java
public class ExampleCommandConfig implements CommandConfig {

    @NotNull
    private final List<String> commandPrefixes = new CopyOnWriteArrayList<>(new String[] {"e!"});

    @NotNull
    @Override
    public List<String> getCommandPrefixes() {
        return commandPrefixes;
    }
}
```
and then using it when creating your CommandManager:
```java
JavacordCommandManager commandManager = new JavacordOptions().configProvider(new ExampleCommandConfig()).create( [DiscordApi instance here] );
```
I'll also immediately add this to the project's wiki, sorry for the inconvenience. Hope this helps!
